
endpoint=https://api.shoonya.com/NorenWClientTP
websocket=wss://api.shoonya.com/NorenWSTP/
eodhost =http =#kurma.kambala.co.in/chartApi/getdata/
debug=false
timeout=7000
heartbeat=3000

NFOSymbolsPath=NFO_symbols.txt

startHour=10
startMin=0
endHour=15
endMin=0

# Only if lotCount is -1, use investmentAmount
lotCount=1
investmentAmount=100000
maxInvestment=50000
auto=false
takePositionInOtherDirection=false

# TODO=Should be smaller closer to expiry. Bigger difference for bidirection
targetPriceDiff=5
stopLossPriceDiff=10
buyAgainPriceDiff=20

# Ideally should be 2x of buyAgainPrice
buyTrail=20

trailStop = true

# OTM is lesser price
optionDirection=OTM 

# TODO=Change every day. On the day of expiry, it should be 0
depth=0

# buy both call and put
bidirection=false

# if call buy call, if put buy put, otherwise calculate. applicable only if bidirection is false
selectedOption=calculate 

#TODO=Buy only when price is low when compared to index value

# Strategies are 
NIFTY_STRATEGY=Strategies.BUY_AND_SELL
BANKNIFTY_STRATEGY=Strategies.BUY_AND_SELL
FINNIFTY_STRATEGY=Strategies.BUY_AND_HOLD