settings:
  minPrice: 20
  maxPrice: 30000
  targetPriceDiff: 2
  stopLossPriceDiff: 11
  trailingDistance: 4
  cooldownSeconds: 0
  logQuotes: false
strategies:
  - type: SentimentStrategy
    enabled: false
    averageThreshold: 20
    targetPrice: 2
    orderQuantity: 7200
    sentiment: put
    loopCount: 1
  - type: BuySellStrategy
    enabled: false
    initialQuantity: 150
    incrementFactor: single
    incrementQuantity: 150
    averageThreshold: 10
    targetPrice: 5
    stopEnabled: false
    activateIntermittentCount: 100
    maxIterationCount: 10
    logEnabled: false
    right: none
  - type: IntermittentStrategy
    enabled: false
    loopCount: 3
    targetPrice: 2
    quantity: 75
    threshold: 10
    logEnabled: false
  - type: RateOfChangeStrategy
    enabled: false
    pointsThreshold: 30
    accelerationThreshold: 5
    numberOfDatapointsReceived: 50
    quantity: 65
    targetPrice: 2
    stopLossPrice: 11
    maxHoldTimeMinutes: 30
    logEnabled: true
  - type: GapStrategy
    enabled: false
    pointsThreshold: 20
    numberOfDatapointsReceived: 50
    quantity: 65
    targetPrice: 10
    stopLossPrice: 5
    maxHoldTimeMinutes: 600
    gapReversalMode: false
    gapReversalThreshold: 100
    logEnabled: true
  - type: RuleBasedStrategy
    enabled: false
    indicators:
      - RSI_5_70_30
    quantity: 65
    target: 10
    stopLoss: 20
    maxHoldTimeMinutes: 30
    logEnabled: true
  - type: GoodMorningStrategy
    enabled: true
    quantity: 650
    targetPoints: 10
    stopLossPoints: 10
    logEnabled: true
    snapshotTime: '13:05'
    confirmTime: '13:10'
    previousClose: 24289
  - type: SupportResistanceStrategy
    enabled: false
    supportPrice: 0
    resistancePrice: 0
    quantity: 1755
    targetPoints: 10
    stopLossPoints: 15
    logEnabled: true
  - type: TargetReachStrategy
    enabled: false
    symbol: NIFTY
    strike: 0
    expiry: '2026-01-01'
    optionType: CE
    targetPrice: 0
    quantity: 1755
    targetPoints: 10
    stopLossPoints: 15
    logEnabled: true
