settings:
  minPrice: 20
  maxPrice: 30000
  targetPriceDiff: 2
  stopLossPriceDiff: 11
  trailingDistance: 4
  cooldownSeconds: 0
  safetyBufferAmount: 5000
  consistencyLimitPercent: 40
strategies:
  - type: SentimentStrategy
    enabled: false
    averageThreshold: 20
    targetPrice: 2
    orderQuantity: 7200
    sentiment: put
    loopCount: 1
  - type: ContinuousStrategy
    enabled: false
    initialQuantity: 75
    slDistance: 10
    squareOffDistance: 50
    minPremium: 100
    allottedCapital: 500000
    maxProfit: 2
    spawnQuantityMode: 3
    averageQuantityMode: same
    right: none
    cooldownSeconds: 60
    logEnabled: true
    momentumEnabled: false
    momentumTimeoutMs: 3000
  - type: RateOfChangeStrategy
    enabled: true
    pointsThreshold: 5
    accelerationThreshold: 1
    numberOfDatapointsReceived: 50
    quantity: 65
    targetPrice: 1
    stopLossPrice: 500
    maxHoldTimeMinutes: 30
    logEnabled: true
  - type: GapStrategy
    enabled: false
    pointsThreshold: 20
    numberOfDatapointsReceived: 50
    quantity: 65
    targetPrice: 10
    stopLossPrice: 5
    maxHoldTimeMinutes: 600
    gapReversalMode: false
    gapReversalThreshold: 100
    logEnabled: true
  - type: RuleBasedStrategy
    enabled: false
    indicators:
      - RSI_5_70_30
    quantity: 65
    target: 10
    stopLoss: 20
    maxHoldTimeMinutes: 30
    logEnabled: true
