name: cbse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # flutter_riverpod: ^1.0.3+1
  hive: ^2.2.3
  http: ^0.13.4
  path_provider: ^2.0.11
  flutter_settings_screens: ^0.3.0-null-safety
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2+1
  # better_player: ^0.0.82
  # video_player: ^2.4.7
  sse_client: ^0.1.0
  universal_html: ^2.0.8
  flutter_client_sse: ^1.0.0
  intl: ^0.17.0
  flutter_riverpod: ^2.3.4
  interactive_chart: ^0.3.4
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  flutter_typeahead: ^5.2.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rename: ^2.0.1
  
flutter:
  uses-material-design: true
  assets:
    - images/books.png
    - assets/contents.json
    - assets/contracts.csv

flutter_icons:
  android: true
  ios: false
  adaptive_icon_foreground: "images/books.png"
  image_path: "images/books.png"